use rltk::{Rltk, VirtualKeyCode};

#[derive(PartialEq, Eq)]
pub enum MapAction {
  #[cfg(debug_assertions)]
  ShowDebugMenu,
  MoveLeft,
  MoveRight,
  MoveUp,
  MoveDown,
  MoveUpLeft,
  MoveUpRight,
  MoveDownLeft,
  MoveDownRight,
  SearchContainer,
  StayStill,
  OpenDoor,
  PickupItem,
  ShowInventoryMenu,
  ShowDropMenu,
  ShowActionMenu,
  ShowEquipmentMenu,
  SearchHidden,
  DisarmTrap,
  ArmTrap,
  GrabFurniture,
  ReleaseFurniture,
  Attack,
  Hide,
  NoAction,
  GoDownStairs,
  GoUpStairs,
  Exit,
  LeaveDungeon,
  Interact,
  ScrollLeft,
  ScrollRight,
  ScrollDown,
  ScrollUp
}

pub fn map_input_to_map_action(ctx: &mut Rltk) -> MapAction {
  match ctx.key {
    None => MapAction::NoAction,
    Some(key) => match key {
      #[cfg(debug_assertions)]
      VirtualKeyCode::Key8 => MapAction::ShowDebugMenu,
      VirtualKeyCode::Escape => MapAction::Exit,
      VirtualKeyCode::A => MapAction::MoveLeft,
      VirtualKeyCode::D => MapAction::MoveRight,
      VirtualKeyCode::W => MapAction::MoveUp,
      VirtualKeyCode::X => MapAction::MoveDown,
      VirtualKeyCode::Q => MapAction::MoveUpLeft,
      VirtualKeyCode::E => MapAction::MoveUpRight,
      VirtualKeyCode::Z => MapAction::MoveDownLeft,
      VirtualKeyCode::C => MapAction::MoveDownRight,
      VirtualKeyCode::V => MapAction::SearchContainer,
      VirtualKeyCode::S => MapAction::StayStill,
      VirtualKeyCode::G => MapAction::OpenDoor,
      VirtualKeyCode::F => MapAction::PickupItem,
      VirtualKeyCode::I => MapAction::ShowInventoryMenu,
      VirtualKeyCode::R => MapAction::ShowDropMenu,
      VirtualKeyCode::M => MapAction::ShowActionMenu,
      VirtualKeyCode::O => MapAction::ShowEquipmentMenu,
      VirtualKeyCode::H => MapAction::SearchHidden,
      VirtualKeyCode::J => MapAction::Hide,
      VirtualKeyCode::T => MapAction::DisarmTrap,
      VirtualKeyCode::P => MapAction::ArmTrap,
      VirtualKeyCode::B => MapAction::GrabFurniture,
      VirtualKeyCode::N => MapAction::ReleaseFurniture,
      VirtualKeyCode::Period => MapAction::GoDownStairs,
      VirtualKeyCode::Comma => MapAction::GoUpStairs,
      VirtualKeyCode::L => MapAction::LeaveDungeon,
      VirtualKeyCode::Y => MapAction::Interact,
      VirtualKeyCode::K => MapAction::Attack,
      VirtualKeyCode::Left => MapAction::ScrollLeft,
      VirtualKeyCode::Right => MapAction::ScrollRight,
      VirtualKeyCode::Up => MapAction::ScrollUp,
      VirtualKeyCode::Down => MapAction::ScrollDown,
      _ => MapAction::NoAction,
    },
  }
}
